# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---

- name: install caddy
  block:
    - name: register lsb release
      command: lsb_release -cs
      register: lsb_release
    - name: add caddy repo
      apt_repository:
        repo: deb [trusted=yes] https://apt.fury.io/caddy/ /
        filename: caddy-fury
        state: present
    - name: goaccess key
      apt_key: 
        url: https://deb.goaccess.io/gnugpg.key
        state: present
    - name: add goaccess repo
      apt_repository:
        repo: deb http://deb.goaccess.io/ {{ lsb_release.stdout }} main
        filename: goaccess
        state: present
    - name: install caddy + goaccess
      apt: name={{ packages }} state=present
      vars:
        packages:
          - caddy
          - goaccess
    - name: install caddy service
      service:
        name: caddy
        enabled: yes
        state: started

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------
- name: create caddyfile
  template:
    src: 'files/Caddyfile.j2'
    dest: '/etc/caddy/Caddyfile'
  notify: restart caddy
