# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---
- name: nginx
  block:
    - name: install nginx package
      apt: name={{ packages }} state=present
      vars:
        packages:
          - nginx
          - python-certbot-nginx
    - name: install nginx service
      service:
        name: nginx
        enabled: yes
        state: started

  when: ansible_os_family == "Debian"
  become: true
