# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---    
- name: install nginx
  block:
    - apt: name={{packages}} state=present
      vars:
        packages:
          - nginx
    - service:
        name: nginx
        enabled: yes
        state: started

  when: ansible_os_family == "Debian"
  become: true
