# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---

- name: apache
  block:
    - name: install apache + certbot packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - rsync
          - apache2
#    - name: Enable apache modules
#      apache2_module:
#        name: "{{ modules }}"
#        state: present
#      vars:
#        modules:
#          - rewrite
#          - ssl
    - name: install apache service
      service:
        name: apache2
        enabled: yes
        state: started

  when: ansible_os_family == "Debian"
  become: true

- name: copy site configs
  copy:
    src: files/sites/
    dest: /etc/apache2/sites-available/
  notify: restart apache

- name: make sites available
  file:
    src: /etc/apache2/sites-available/{{ item }}.conf
    dest: /etc/apache2/sites-enabled/{{ item }}.conf
    state: link
  notify: restart apache
  with_items:
    - ganymed-it-de
    - ganymed-it-de-ssl
    - kirsten-klomp-de
    - kirsten-klomp-de-ssl
    - lnk-to-me
    - lnk-to-me-ssl
    - psychologische-psychotherapeutin-de
    - psychologische-psychotherapeutin-de-ssl
    - robots-de
    - robots-de-ssl
    - uwe-arzt-de
    - uwe-arzt-de-ssl
    - uwearzt-de
    - uwearzt-de-ssl

# - name: certificates
#   block:
#     - name: check my account
#       acme_account:
#         acme_version: 2
#         account_key_src: /etc/pki/cert/private/account.key
#         state: present
#         allow_creation: yes
#         contact:
#           - mailto:letsencrypt@uwe-arzt.de
#   become: true

