# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install pass packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - pass

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: macOS base install
  block:
    - name: homebrew install packages
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - pass
          - pass-otp

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
- name: install password-store
  git:
    repo: ssh://arche/data/git/password-store.git
    dest: .password-store
