# ------------------------------------------------------------------------------
# Copyright 2017-2018 by Uwe Arzt mailto:mail@uwe-arzt.de, https://uwe-arzt.de
# under BSD License, see https://uwe-arzt.de/bsd-license
# ------------------------------------------------------------------------------
---    
- name: apt install base packages 
  block:
    - apt: name={{item}} state=present update_cache=yes
      with_items:
        - mosh
        - lsof
        - htop
        - fish
        - git
        - apt-transport-https

    - user:
        name: uwe
        shell: /usr/bin/fish

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: brew install base packages
  block:
    - homebrew: 
        name: "{{item}}" 
        state: present
        update_homebrew: yes
      with_items:
        - mosh
        - lsof
        - htop
        - fish
        - git

    - lineinfile:
        path: /etc/shells
        line: /usr/local/bin/fish
      become: true

    - user: 
        name: uwe 
        shell: /usr/local/bin/fish
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: copy config.fish
  copy: 
    src: files/config.fish 
    dest: ~/.config/fish/
    backup: yes
- name: copy fish functions
  copy: 
    src: files/fish.functions/
    dest: ~/.config/fish/functions/
    backup: yes

- name: copy .gitconfig
  copy: 
    src: files/gitconfig
    dest: ~/.gitconfig
    backup: yes
