# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install base packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - aptitude
          - lsof
          - htop
          - zsh
          - git
          - vim
          - rsync
          - sudo
          - curl
          - apt-transport-https
          - screen
          - pass
          - needrestart
    - name: create user
      user:
        name: uwe
        shell: /usr/bin/zsh

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: macOS base install
  block:
    - name: homebrew install packages
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - vim
          - rsync
          - curl
          - screen
          - pass
          - pass-otp

    - name: create user
      user:
        name: uwe
        shell: /bin/zsh
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
- name: copy gitconfig
  copy:
    src: files/gitconfig
    dest: .gitconfig

# ------------------------------------------------------------------------------
- name: install password-store
  git:
    repo: ssh://arche/data/git/password-store.git
    dest: .password-store

# ------------------------------------------------------------------------------
- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: .oh-my-zsh
- name: copy zshrc
  copy:
    src: zshrc
    dest: .zshrc
- name: copy zshenv
  copy:
    src: zshenv
    dest: .zshenv
- name: copy zsh theme
  copy:
    src: uwe.zsh-theme
    dest: .oh-my-zsh/themes/

# ------------------------------------------------------------------------------
- name: add sudoers
  template:
    src: 'template/sudoers.d.j2'
    dest: '/etc/sudoers.d/{{ item.name }}'
  with_items:
    - "{{ sudoers }}"
  become: true
