# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---    
- name: apt install base packages 
  block:
    - apt: name={{packages}} state=present 
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - neovim
          - rsync
          - sudo
          - curl
          - apt-transport-https
          - qtpass
    - user:
        name: uwe
        shell: /usr/bin/fish

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: brew install base packages
  block:
    - homebrew: 
        name: "{{packages}}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - neovim
          - rsync
          - curl

    - lineinfile:
        path: /etc/shells
        line: /usr/local/bin/fish
      become: true

    - user: 
        name: uwe 
        shell: /usr/local/bin/fish
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: copy config.fish
  copy: 
    src: files/config.fish 
    dest: .config/fish/
    backup: yes
- name: copy fish functions
  copy: 
    src: files/fish.functions/
    dest: .config/fish/functions/
    backup: yes
- name: add fisher modules
  command: fish -c fisher add edc/bass
  ignore_errors: yes

- name: copy .gitconfig
  copy: 
    src: files/gitconfig
    dest: .gitconfig
    backup: yes

# ------------------------------------------------------------------------------
- name: add sudoers
  template:
    src: 'template/sudoers.d.j2'
    dest: '/etc/sudoers.d/{{item.name}}'
  with_items:
    - "{{sudoers}}"
  become: true
