# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install base packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - aptitude
          - lsof
          - htop
          - fish
          - git
          - neovim
          - rsync
          - sudo
          - curl
          - apt-transport-https
          - screen
          - pass
    - name: create user
      user:
        name: uwe
        shell: /usr/bin/fish

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: macOS base install
  block:
    - name: homebrew install packages
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - neovim
          - rsync
          - curl
          - screen
          - pass
          - pass-otp

    - name: add fish shell
      lineinfile:
        path: /etc/shells
        line: /usr/local/bin/fish
      become: true

    - name: create user
      user:
        name: uwe
        shell: /usr/local/bin/fish
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: copy config.fish
  copy:
    src: files/config.fish
    dest: .config/fish/
    backup: yes
- name: copy fish functions
  copy:
    src: files/fish.functions/
    dest: .config/fish/functions/
    backup: yes
- name: add fisher modules
  command: fish -c fisher add edc/bass
  ignore_errors: yes

- name: copy .gitconfig
  copy:
    src: files/gitconfig
    dest: .gitconfig
    backup: yes

# ------------------------------------------------------------------------------
- name: add sudoers
  template:
    src: 'template/sudoers.d.j2'
    dest: '/etc/sudoers.d/{{ item.name }}'
  with_items:
    - "{{ sudoers }}"
  become: true
