# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
- import_tasks: handlers/main.yml

- name: restart apache
  service:
    name: apache2
    state: restarted