# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

- import_tasks: handlers/main.yml

- name: restart docker
  service:
    name=docker
    state=restarted
  become: true
