# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---

# ------------------------------------------------------------------------------
- name: check rustup
  stat:
    path: $HOME/.cargo/bin/rustup
  register: rustup
- name: install rustup
  command: curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: not rustup.stat.exists

# ------------------------------------------------------------------------------
- name: install nightly
  command: rustup toolchain install {{ item }}
  with_items:
    - nightly
  ignore_errors: yes
# ------------------------------------------------------------------------------
- name: default nightly
  command: rustup default nightly
  ignore_errors: yes

# ------------------------------------------------------------------------------
- name: add additional rust components
  block:
    - name: add rust components
      command: rustup component add {{ item }}
      with_items:
        - rustfmt-preview

    - name: add crates
      command: cargo install {{ item }}
      with_items:
        - ripgrep
        - cobalt-bin
        - cargo-update
        - cargo-outdated
        - cargo-script
      ignore_errors: yes
  when: ansible_architecture != "armv7l"