# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---

# ------------------------------------------------------------------------------
- name: check rustup
  stat:
    path: $HOME/.cargo/bin/rustup
  register: rustup
- name: install rustup
  command: curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: not rustup.stat.exists

# ------------------------------------------------------------------------------
- name: add additional rust components
  block:
    - name: add rust components
      command: rustup component add {{ item }}
      with_items:
        - rls

    - name: add crates
      command: cargo install {{ item }}
      with_items:
        - cargo-update
        - cargo-audit
      ignore_errors: yes
  when: ansible_architecture != "aarch64"
