# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install base packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - aptitude
          - lsof
          - htop
          - zsh
          - git
          - vim
          - rsync
          - sudo
          - curl
          - apt-transport-https
          - screen
          - mosh
          - pass
          - needrestart
          - tmux
          - ripgrep
          - minicom
    - name: change shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: macOS base install
  block:
    - name: homebrew install packages
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - lsof
          - htop
          - git
          - vim
          - rsync
          - curl
          - screen
          - mosh
          - tmux
          - ripgrep
          - minicom
    - name: change shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
- name: copy gitconfig
  copy:
    src: files/gitconfig
    dest: .gitconfig

# ------------------------------------------------------------------------------
- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: .oh-my-zsh
- name: copy zshrc
  copy:
    src: zshrc
    dest: .zshrc
- name: copy zshenv
  copy:
    src: zshenv
    dest: .zshenv
- name: copy zsh theme
  copy:
    src: uwe.zsh-theme
    dest: .oh-my-zsh/themes/

# ------------------------------------------------------------------------------
- name: copy tmux settings
  copy:
    src: tmux.conf
    dest: .tmux.conf

# ------------------------------------------------------------------------------
- name: add sudoers
  template:
    src: 'files/sudoers.d.j2'
    dest: '/etc/sudoers.d/{{ item.name }}'
  with_items:
    - "{{ sudoers }}"
  become: true
