# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install base packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - rsync
          - sudo
          - curl
          - apt-transport-https
          - needrestart
          - tmux
          - ripgrep
          - neovim
          - python3-pip
    - name: change shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/fish

  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: macOS base install
  block:
    - name: homebrew install packages
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - lsof
          - htop
          - fish
          - git
          - rsync
          - curl
          - tmux
          - ripgrep
          - neovim
    - name: change shell
      user:
        name: "{{ ansible_user_id }}"
        shell: /opt/homebrew/bin/fish
      become: true

  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
- name: Install pip packages
  ansible.builtin.pip:
    name:
      - pynvim

# ------------------------------------------------------------------------------
- name: copy config.fish
  copy:
    src: files/config.fish
    dest: .config/fish/

# ------------------------------------------------------------------------------
- name: copy gitconfig
  copy:
    src: files/gitconfig
    dest: .gitconfig

# ------------------------------------------------------------------------------
- name: copy tmux settings
  copy:
    src: tmux.conf
    dest: .tmux.conf

# ------------------------------------------------------------------------------
- name: add sudoers
  template:
    src: 'files/sudoers.d.j2'
    dest: '/etc/sudoers.d/{{ item.name }}'
  with_items:
    - "{{ sudoers }}"
  become: true
