# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install base packages
  block:
    - name: add podman repo
      apt_repository:
        repo: ppa:projectatomic/ppa
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - podman

  when: ansible_os_family == "Debian"
  become: true
