# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: ros2
  block:
    - name: install needed packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - gnupg2
          - lsb-release
          - python3-argcomplete

    - name: add ros2 repo key
      apt_key:
        url: http://repo.ros2.org/repos.key
        state: present

    - name: add ros2 repo
      apt_repository:
        repo: deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu {{ ansible_distribution_release }} main
        filename: ros2
        state: present

    - name: install ros2 base
      apt: name={{ packages }} state=present update_cache=yes
      vars:
        packages:
          - ros-humble-ros-base

  when: ansible_os_family == "Debian"
  become: true
