# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---    
- name: apt install base gui packages 
  block:
    - apt: name={{packages}} state=present 
      vars:
        packages:
          - qtpass
  when: ansible_os_family == "Debian"
  become: true

# ------------------------------------------------------------------------------

- name: brew cask install base gui packages
  block:
    - homebrew_cask: 
        name: "{{packages}}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - qtpass
          - sizeup
  when: ansible_os_family == "Darwin"