# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

- name: restart prometheus-node-exporter
  block:
    - command: launchctl unload /Library/LaunchDaemons/de.uwearzt.prometheus-node-exporter.plist
      ignore_errors: true
    - command: launchctl load /Library/LaunchDaemons/de.uwearzt.prometheus-node-exporter.plist 
  when: ansible_os_family == "Darwin"

- name: restart prometheus-node-exporter
  service:
    name=prometheus-node-exporter
    state=restarted
  become: true
  when:  ansible_os_family == "Debian"