# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: prometheus server
  block:
    - name: apt
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - prometheus

    - name: install service
      service:
        name: prometheus
        enabled: yes
        state: started
  become: true
  when: ansible_os_family == "Debian"

- name: prometheus configuration
  block:
    - template:
        src: 'template/prometheus.yml.j2'
        dest: '/etc/prometheus/prometheus.yml'
  become: true

- name: install grafana
  block:
    - name: grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
    - name: grafana repo key
      apt_key:
        url: https://packages.grafana.com/gpg.key
    - name: apt
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - grafana

    - name: install service
      service:
        name: grafana-server
        enabled: yes
        state: started
  become: true

- name: grafana configuration
  block:
    - template:
        src: 'template/grafana.ini.j2'
        dest: '/etc/grafana/grafana2.ini'
  become: true