# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---    
- name: prometheus server
  block:
    - homebrew: 
        name: "{{packages}}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - prometheus
          - grafana
    - user: 
        name: prometheus
        create_home: yes 
        system: yes
      become: true

- name: prometheus configuration
  block:
    - file: 
        path: '/etc/prometheus'
        state: directory
    - template:
        src: 'template/prometheus.yml.j2'
        dest: '/etc/prometheus/prometheus.yml'
    - copy: 
        src: 'files/prometheus.plist'
        dest: /Library/LaunchDaemons/
  become: true