@startuml network
nwdiag {
  network dg {
    router;
  }
  network telekom {
    draytek;
  }
  network external {
    address = "172.x.x.x/24";

	  router [address = "172.x.x.1"];
	  draytek [address = "172.x.x.2"];

    firewall;
  }
}
@enduml
