# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------
---    
- name: install openvpn server
  block:
  - homebrew:
      name: "{{packages}}"
      state: present 
      update_homebrew: yes
    vars:
      packages:
        - openvpn
        - stunnel

  when: ansible_os_family == "Darwin"