# ------------------------------------------------------------------------------
# Copyright 2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: wireguard
  block:
    - name: install wireguard
      apt: name={{ packages }} state=present update_cache=yes
      vars:
        packages:
          - wireguard

  when: ansible_os_family == "Debian"
  become: true
