# ------------------------------------------------------------------------------
# Copyright 2018-2019 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

- name: brew cask install base gui packages
  block:
    - name: gui packages
      homebrew_cask:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - gpg-suite
          - wireshark
          - brewservicesmenubar
          # - visual-studio-code
  when: ansible_os_family == "Darwin"