# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: prometheus client
  block:
    - name: homebrew
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: yes
      vars:
        packages:
          - node_exporter
      register: restart prometheus-node-exporter
    - name: copy launchd
      copy:
        src: files/de.uwearzt.prometheus-node-exporter.plist
        dest: /Library/LaunchDaemons/
      become: true
      register: restart prometheus-node-exporter
  when: ansible_os_family == "Darwin"

- name: prometheus client
  block:
    - name: apt
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - prometheus-node-exporter

    - name: install service
      service:
        name: prometheus-node-exporter
        enabled: yes
        state: started
  become: true
  when: ansible_os_family == "Debian"

