# ------------------------------------------------------------------------------
# Copyright 2019 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: install tick stack
  block:
  - name: add tick repo key
    apt_key:
      url: https://repos.influxdata.com/influxdb.key
      state: present

  - name: add tick repo
    apt_repository:
      repo: deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable
      filename: tick
      state: present

  - name: apt
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - telegraf

  - name: copy telegraf.conf
    copy:
      src: telegraf.conf
      dest: /etc/telegraf/telegraf.conf
    notify: restart telegraf

  - name: install telegraf service
    service:
      name: telegraf
      enabled: yes
      state: started
  become: true
  when: ansible_os_family == "Debian"

- name: install tick stack
  block:
  - name: homebrew install packages
    homebrew:
      name: "{{ packages }}"
      state: present
      update_homebrew: yes
    vars:
      packages:
        - telegraf
  - name: copy telegraf.conf
    copy:
      src: telegraf.conf
      dest: /usr/local/etc/telegraf.conf
    # notify: restart telegraf
    become: true
  when: ansible_os_family == "Darwin"
