# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---    
- name: brew install
  block:
  - homebrew:
      name: "{{packages}}"
      state: present 
      update_homebrew: yes
    vars:
      packages:
        - docker
        - docker-clean

  when: ansible_os_family == "Darwin"

- name: apt install docker
  block:
    - apt: name={{packages}} state=present 
      vars:
        packages:
          - docker

  when: ansible_os_family == "Debian"
  become: true
