export ZSH=.oh-my-zsh

# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

export EDITOR='nvim'

alias code="code-insiders"
alias hg="history | grep"
alias vi="nvim"
