# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- import_playbook: arche.yml
- import_playbook: webserver.yml
- import_playbook: devel.yml
- import_playbook: rosdevel.yml
- import_playbook: rpi.yml
