# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: Cisco Switch
  hosts: c2960l
  connection: network_cli
  gather_facts: no
  become: yes

  tasks:
  - ios_facts:
      gather_subset: all
  - debug:
      msg: "IOS version: {{ ansible_net_version }}"

  # --------------------------------------------------------------
  - name: settings
    ios_config:
      commands:
        - "ip scp server enable"
        - "aaa authorization exec default local if-authenticated"
        - "snmp-server community ro-snmp RO "

  # --------------------------------------------------------------
  # VLANs
  - ios_vlan:
      vlan_id: 40
      name: guest
      state: present
      interfaces:
        - GigabitEthernet0/1
        - GigabitEthernet0/2

  - ios_vlan:
      vlan_id: 60
      name: homeautomation
      state: present
      interfaces:

  # --------------------------------------------------------------
  # Access Points
  - ios_l2_interface:
      name: GigabitEthernet0/23
      mode: trunk
      native_vlan: 1
      trunk_allowed_vlans: 1,40,60
      trunk_vlans: 40,60
  - ios_l2_interface:
      name: GigabitEthernet0/24
      mode: trunk
      native_vlan: 1
      trunk_allowed_vlans: 1,40,60
      trunk_vlans: 40,60


  # --------------------------------------------------------------
  # Routing
