# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: Development machines
  hosts: devel
  roles:
    - network
    - base-cmd
    - pass
    - base-gui
    - devel
    - rust
