# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: Cisco Switch
  hosts: c2960l
  connection: network_cli
  gather_facts: no
  # become: yes

  tasks:
  - ios_facts:
      gather_subset: all

  - name: show poe devices
    ios_command:
      commands: show power inline