# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: Cisco Switch
  hosts: c2960l
  connection: network_cli
  gather_facts: no
  become: yes

  vars:
    ios_version: 15.2(7)E3
    image_name: c2960l-universalk9-mz.152-7.E3.bin

  tasks:
  - ios_facts:
      gather_subset: all
  - debug:
      msg: "IOS version: {{ ansible_net_version }}"

  # --------------------------------------------------------------
  # upgrade
  - name: upgrade
    block:
      - name: copy boot image
        ios_command:
          commands:
            - "scp /Users/uwe/Downloads/{{ image_name }} {{ inventory_hostname }}:{{ image_name }}"
      - name: set boot to new image
        ios_config:
          commands:
            - "boot system flash:{{ image_name }}"
      - name: reboot with new image
        ios_command:
          commands:
            - "write memory"
            - command: 'reload'
              prompt: '\[confirm\]'
              answer: 'y'

    when: ansible_net_version != ios_version

