# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: Cisco Switch
  hosts: c2960l
  connection: network_cli
  gather_facts: no
  become: yes

  vars:
    ios_version: 15.2(7)E0a
    image_name: c2960l-universalk9-mz.152-7.E0a.bin

  tasks:
  - ios_facts:
      gather_subset: all
  - debug:
      msg: "IOS version: {{ ansible_net_version }}"

  # --------------------------------------------------------------
  # upgrade
  - name: upgrade
    block:
      - name: copy ios image
        command: "scp /Users/uwe/Downloads/{{image_name}} {{inventory_hostname}}:{{image_name}}"

      - name: set boot to new image
        ios_config:
          commands:
            - "boot system flash:{{image_name}}"

      - name: save actual config
        ios_config:
          commands:
            - "write memory"

      - debug:
        msg: "Restart required for activating new version"
      #- name: reboot
      #  ios_command:
      #    commands:
      #    - command: 'reload'
      #      prompt: '\[confirm\]'
      #      answer: 'y'

    when: ansible_net_version != ios_version

