# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: upgrade everything
  hosts: all

  tasks:
# ------------------------------------------------------------------------------
  - name: update debian packages
    block:
      - apt:
          upgrade: dist
          update_cache: yes
    when: ansible_os_family == "Debian"
    become: true

# ------------------------------------------------------------------------------
  - name: update apple packages
    block:
      - name: softwareupdate
        command: softwareupdate --install --all
        become: true
      - name: brew upgrade
        homebrew: 
          update_homebrew: yes 
          upgrade_all: yes
      - name: brew cask upgrade
        homebrew_cask:
          update_homebrew: no 
          upgrade_all: true
      - name: remove old brew versions
        command: brew cleanup
    when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
  - name: check rustup, update everything if needed
    stat:
      path: $HOME/.cargo/bin/rustup
    register: rustup

  - name: upgrade rust
    block: 
      - shell: rustup self update
      - shell: rustup update
    when: rustup.stat.exists == True
  - name: upgrade rust packages
    block: 
      - shell: cargo install-update --all 
    when: rustup.stat.exists == True and
           ansible_architecture != "armv7l"
