# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: upgrade everything
  hosts: devel:server:webserver:rosdevel

  tasks:
# ------------------------------------------------------------------------------
  - name: update debian
    block:
      - name: apt upgrade
        apt:
          upgrade: dist
          update_cache: yes
    when: ansible_os_family == "Debian"
    become: true

# ------------------------------------------------------------------------------
  - name: update apple packages
    block:
      - name: softwareupdate
        command: softwareupdate --install --all
        become: true
      - name: brew upgrade
        homebrew:
          update_homebrew: yes
          upgrade_all: yes
      - name: brew cask upgrade
        homebrew_cask:
          update_homebrew: no
          upgrade_all: true
      - name: remove old brew versions
        command: brew cleanup
    when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------
  - name: check rustup, update everything if needed
    stat:
      path: $HOME/.cargo/bin/rustup
    register: rustup

  - name: rustup
    block:
      - name: self update
        command: rustup self update
      - name: update
        command: rustup update
    when: rustup.stat.exists
  - name: upgrade rust packages
    block:
      - name: cargo update
        command: cargo install-update --all
    when: rustup.stat.exists and
           ansible_architecture != "aarch64"
