# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and 
# limitations under the License.
# ------------------------------------------------------------------------------

---

- name: brew install
  block:
  - homebrew:
      name: "{{item}}"
      state: present 
      update_homebrew: yes
    with_items:
      - curl

  # - homebrew_tap:
  #    name: caskroom/cask
  #    state: present
  
  - homebrew_cask:
      name: "{{item}}"
      state: present
    with_items:
      - 1password-cli
  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: dnf install
  become: true
  dnf: 
    name: "{{item}}"
  with_items:
    - curl
    - rust
    - git
    - cargo
  when: ansible_os_family == "RedHat"

# ------------------------------------------------------------------------------

- name: dnf install raspberry
  become: true
  dnf: 
    name: "{{item}}"
  with_items:
    - i2c-tools
    - libi2c
    - libi2c-devel
  when: ansible_os_family == "RedHat" and
        ansible_system_vendor == "raspberrypi"
