# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---

- name: brew install
  block:
  - homebrew:
      name: "{{packages}}"
      state: present 
      update_homebrew: yes
    vars:
      packages:
        - mosh

  # - homebrew_tap:
  #    name: caskroom/cask
  #    state: present
  
  - homebrew_cask:
      name: "{{packages}}"
      state: present
    vars:
      packages:
        - 1password-cli
  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: apt install
  become: true
  apt: 
    name: "{{packages}}"
  vars:
    packages:
      - mosh
      - gcc
      - g++
      - make
      - libssl-dev
      - pkg-config
  when: ansible_os_family == "Debian"

# ------------------------------------------------------------------------------

- name: apt install raspberry
  become: true
  apt: 
    name: "{{packages}}"
  vars:
    packages:
      - i2c-tools
      - libi2c-dev
      - gpiod
      - libgpiod-dev
      - raspi-gpio
  when: ansible_os_family == "Debian" and
        ansible_architecture == "armv7l"
