# ------------------------------------------------------------------------------
# Copyright 2018-2020 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---

- name: install packges
  block:
  - name: homebrew
    homebrew:
      name: "{{ packages }}"
      state: present
      update_homebrew: yes
    vars:
      packages:
        - mosh
        - ansible
        - ansible-lint
  when: ansible_os_family == "Darwin"

# ------------------------------------------------------------------------------

- name: apt install packages
  become: true

  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mosh
      - gcc
      - g++
      - make
      - libssl-dev
      - pkg-config
  when: ansible_os_family == "Debian"

# ------------------------------------------------------------------------------

- name: raspberry
  block:
    - name: apt install raspberry
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - i2c-tools
          - libi2c-dev
          - gpiod
          - libgpiod-dev
          # - raspi-gpio
    - name: add user to spi/i2c group
      user:
        name: uwe
        groups: i2c,input
        append: yes
  when: ansible_os_family == "Debian" and
        ansible_architecture == "armv7l" or ansible_architecture == "aarch64"
  become: true
