# ------------------------------------------------------------------------------
# Copyright 2022 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: apt install kvm packages
  block:
    - name: apt install packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - bridge-utils
          - qemu
          - virtinst

  when: ansible_os_family == "Debian"
  become: true
