# ------------------------------------------------------------------------------
# Copyright 2018 Uwe Arzt, mail@uwe-arzt.de
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------------

---
- name: kvm
  block:
    - name: install needed packages
      apt: name={{ packages }} state=present
      vars:
        packages:
          - qemu
          - qemu-kvm
          - libvirt-bin
          - bridge-utils
          - virtinst

    - name: install service libvirtd
      service:
        name: libvirtd
        enabled: yes
        state: started

  when: ansible_os_family == "Debian"
  become: true
